jobs:
include:
  - stage: build
    script:
      - yarn
      - yarn test
      - yarn build
  - stage: deploy to pages
    script: skip
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $github_token
      local_dir: build
      on:
        branch: master
  - stage: post production
    script: 
      - yarn lh -- https://chachakawooka.github.io/ux-playbook/
    on:
        branch: gh-pages