language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - build
jobs:
  include:
    - stage: build
      script:
        - yarn
        - yarn test
        - yarn build
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          branch: master
    - stage: post
      script: 
        - yarn lh -- https://chachakawooka.github.io/ux-playbook/
      on:
          branch: gh-pages